### ISSUE TITLE
[proposed label:question] caldav driver one way sync?

### ISSUE THREAD

**Issue by kevin75001** [JodliDev/calendar#10]
Hi,

Just to have a confirmation, does caldav driver sync only in one way (plugin to caldav server)?

If it's a one way sync, does it's planned to add sync from server to cache db?

If not planned, is there some limitation anywhere that make impossible to implement two way sync?

**Comment by JodliDev** [comment]
Sorry for my late reply.
Its two way sync. So changes in the plugin are uploaded to the external server. And changes in the external server will be synced into the plugin.

Except ics support of course because they are always read only
