### ISSUE TITLE
Calendars deleted outside of roundcube will not be removed from roundcube.

### ISSUE THREAD

**Issue by JodliDev** [JodliDev/calendar#13]
CalDAV has no event updates for deleting a calendar, meaning that when a user deletes a calendar from the CalDAV source outside of roundcube, this plugin will never be informed about it.

That means that after a calendar is deleted only in the CalDAV source:

- The calendar will still be listed in roundcube calendar (because it is still cached)
- Events from that calendar will also still be displayed (since they are also still cached and were never explicitly deleted)
- Deleting, adding or modifying events will not work and only lead to errors.
- Updating the calendar will create an error message (leading to spammed errors when the calendar only is just opened).

This also affects #5 meaning that preinstalled sources will not reinstated in the source because roundcube will believe they are still there.

I am not sure how best to deal with that. I guess the error message returned by a CalDAV server probably has confirmation that the calendar does not exist anymore and can be safely deleted. But I havent done any testing in this regard.

**Comment by chaos-prevails** [comment]
Maybe one solution could be to add a parameter in the config whether to query for existing calendars upon login / opening the calendar view (maybe better upon login, so whenever one needs to accept an invitation sent by email, the list of available calendars is already updated)?

e.g. carddav plugin has a parameter for the predefined resources to query the list of available address books every time of login. that way dependent how predefined resources are configured, the list of available calendars is up to date
