### ISSUE TITLE
MySQL database update problem

### ISSUE THREAD

**Issue by IgorA100** [JodliDev/calendar#28]
MariaDB Server version: 10.1.37
my.cnf:
```
...
innodb_large_prefix=true
innodb_file_format=Barracuda
...
```
`# bin/initdb.sh --dir=plugins/calendar/drivers/caldav/SQL
Creating database schema... ERROR: [1709] Index column size too large. The maximum column size is 767 bytes. (SQL Query: CREATE TABLE IF NOT EXISTS `caldav_calendars` (
    `calendar_id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` int(10) UNSIGNED NOT NULL DEFAULT '0',
    `source_id` int(10) UNSIGNED DEFAULT NULL,
    `name` varchar(255) CHARACTER SET utf8mb4 NOT NULL,
    `color` varchar(8) NOT NULL,
    `showalarms` tinyint(1) NOT NULL DEFAULT '1',
    `caldav_tag` varchar(255) DEFAULT NULL,
    `caldav_url` varchar(1024) NOT NULL,
    `caldav_last_change` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_ical` tinyint(1) NOT NULL DEFAULT '0',
    `ical_user` varchar(255) DEFAULT NULL,
    `ical_pass` varchar(1024) DEFAULT NULL,
    PRIMARY KEY(`calendar_id`),
    INDEX `caldav_user_name_idx` (`user_id`, `name`),
    CONSTRAINT `fk_caldav_calendars_user_id` FOREIGN KEY (`user_id`)
        REFERENCES `users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_caldav_calendars_sources` FOREIGN KEY (`source_id`)
        REFERENCES `caldav_sources`(`source_id`) ON DELETE CASCADE ON UPDATE CASCADE
) /*!40000 ENGINE=INNODB */ /*!40101 CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */)
[FAILED]
ERROR: [1709] Index column size too large. The maximum column size is 767 bytes.
`

**Comment by JodliDev** [comment]
Sorry for never replying.
It looks to me that this is an issue with your database.
I assume that this issue has been resolved. If not please let me know :)
