### ISSUE TITLE
Synchronization attachments to events

### ISSUE THREAD

**Issue by IgorA100** [JodliDev/calendar#29]
At the moment, the calendar in NextCloud does not officially support attachments yet, but a good person decided to correct this misunderstanding! Here is the pull request: https://github.com/nextcloud/calendar/pull/4251
I looked at this calendar and it already works with attachments.
I was unable to sync attachments with NextCloud with your version of the CalDAV driver.
It would be really great if you implemented attachment sync!!!

**Comment by JodliDev** [comment]
As far as I understand, this is not an issue of this caldav implementation but a missing feature of the roundcube/calendar in general.
So you would have to ask them. Their repository is here:
https://git.kolab.org/diffusion/RPK/browse/master/plugins/calendar/

I am closing this for now :)
