### ISSUE TITLE
Event notification missing time

### ISSUE THREAD

**Issue by loopguard404** [JodliDev/calendar#37]
When you create an event in the calendar, a message is sent with an invitation to the event. But this prompt is missing the time of the scheduled event.

In Thunderbird, the time of the scheduled event is displayed.

![image](https://user-images.githubusercontent.com/46474603/233609032-6be1a88f-c3a2-485c-827e-48f77db18025.png)

**Comment by JodliDev** [comment]
See https://github.com/JodliDev/calendar/issues/38#issuecomment-1525462411
