### ISSUE TITLE
Commit composer lockfile in git ?

### ISSUE THREAD

**Issue by n-peugnet** [JodliDev/calendar#9]
Composer [recommends adding the lockfile to the VCS](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control). I know the lockfile [will not be used when installing this plugin the recommended way](https://getcomposer.org/doc/02-libraries.md#lock-file), but this could still be useful for development setup to speedup composer dependency resolving. Otherwise it could be added to the `.gitignore` (along with the `vendor` directory).

Edit: after some thinking this could lead to issues when updating the sources from upstream project. It may be better to ignore it.

**Comment by JodliDev** [comment]
SInce the original project does not have it, I think its best to leave it as is - just to stay in sync as much as possible :)
